version: "3.7"

services:

  portainer:
    restart: unless-stopped
    image: portainer/portainer:latest
    hostname: portainer
    container_name: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
